### ISSUE TITLE
Update Cypress 7.* to peerDependencies

### ISSUE THREAD

**Issue by jimfm** [javierbrea/cypress-localstorage-commands#285]
**Is your feature request related to a problem? Please describe.**
Hardcoded dependencies need to have 7.* added.

**Describe the solution you'd like**
Update peerDependency

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by javierbrea** [comment]
Hi @jimfm,

Thanks for advising about the new Cypress version! 🙂  The renovate bot is configured in the project, but it waits three days before updating any new version in order to ensure its stability.

Dependencies are intentionally hardcoded because the Cypress version in e2e tests has to be updated in order to check that the plugin continues working properly. Anyway, I have manually updated the dependency in the e2e tests and published a [new release supporting v7.x](https://github.com/javierbrea/cypress-localstorage-commands/releases/tag/v1.4.3).
