### ISSUE TITLE
LocalStorage missing across spec files

### ISSUE THREAD

**Issue by aasimali** [javierbrea/cypress-localstorage-commands#401]
. I installed this plugin using `npm i --save-dev cypress-localstorage-commands`

. And I added this line: `import "cypress-localstorage-commands"` into cypress/support/commands.js

. In my testcase.ts file, I added

![image](https://user-images.githubusercontent.com/90683113/161750075-3805408b-9b97-40d3-a740-8316fc07b460.png)

And when I execute, it does not store cookies

<img width="383" alt="image" src="https://user-images.githubusercontent.com/10045599/161750811-99d406be-1aee-45a8-aab2-72538753b114.png">

**Comment by javierbrea** [comment]
Hi @aasimali,

Could you please provide more information about how is the localStorage saved when the page performs the login action? Or even better, could you provide a fully reproducible example of the case in which the plugin is not working? To ensure that it is the plugin which is not working, maybe you can try to test the plugin simply setting one item in the localStorage, and then check that it is still present after restoring it. 

Thanks in advance

**Comment by aasimali** [comment]
Hi @javierbrea 

Thanks for your response, the issue is from Instagram login.

To reproduce it, please log into Instagram and once you're successfully logged in one test, then see you still have cookies from Instagram or not.

In my test, I'm logging into Instagram first as I needed to logged in Instagram to perform the next test, but as cookies is flushing, I'm not able to perform the test.

**Comment by javierbrea** [comment]
Could you please be more specific and provide some code with a reproducible failing example, please? A link to a repository containing a failing test would be great, for example. On the contrary, please give more clues about what can be failing. Are you sure that the login is stored in the local storage? It is stored in the same domain or in another? Traces? Screenshots of developer tools?
Note that I can't set up a complete project with the unique clue being that it is failing in "Instagram". First I would like to have enough context and information in order to discard other possible causes.

**Comment by DiederikvandenB** [comment]
I am also having this issue. Don't have time to setup a demo repo right now unfortunately.

**Comment by alex-clear** [comment]
@javierbrea Just used your plugin and faced with this issue
Cypress version 10.2.0

Here my local storage view:
<img width="1281" alt="Screen Shot 2022-06-22 at 10 24 22" src="https://user-images.githubusercontent.com/97834715/174969669-a7a742d7-92da-4ea5-8b8a-94443a30f930.png">

As you can see I have 2 keys in local storage

However, after my tests go to next test the local storage was disappeared
I set the debugger inside you plugin and found that local storage inside you code is empty:
<img width="1039" alt="Screen Shot 2022-06-22 at 10 30 10" src="https://user-images.githubusercontent.com/97834715/174970632-b3361d83-62c5-4706-b993-dd44f59dbe62.png">
Here are my cypress configurations:
<img width="1073" alt="Screen Shot 2022-06-22 at 10 38 44" src="https://user-images.githubusercontent.com/97834715/174971927-5ca67ada-0cad-4855-9c07-28ae7ce35d48.png">
<img width="1046" alt="Screen Shot 2022-06-22 at 10 38 20" src="https://user-images.githubusercontent.com/97834715/174971940-a6e044cb-a0f7-45f3-a883-de2b48b6d7d9.png">
<img width="763" alt="Screen Shot 2022-06-22 at 10 37 15" src="https://user-images.githubusercontent.com/97834715/174971950-72a28c45-7b26-476d-8011-ac1347750dfe.png">

And here is my test code:
<img width="481" alt="Screen Shot 2022-06-22 at 10 40 16" src="https://user-images.githubusercontent.com/97834715/174972550-9ffae06f-b563-45b8-8b7a-26ded0612179.png">

I hope this will help you to investigate the issue and provide me what I am doing wrong or fix the issue from you side.
Thanks for help

**Comment by javierbrea** [comment]
Hi @DiederikvandenB , are tests in the same specs file or in different files?

**Comment by vdineva** [comment]
@javierbrea I am also having issues with this plugin since upgrading to Cypress 10. In my case tests are in different files

**Comment by peeyushohri04** [comment]
@javierbrea  i am also facing issues post upgrading to cypress 10 . Local storages are not being retained across specs . Is there any fix in pipeline to resolve this issue ?

**Comment by javierbrea** [comment]
Hi @vdineva,
I'm adding some tests to the package, and, after executing them with previous versions I have discovered that the issue was also happening on Cypress v9.7.0. The localStorage was not retained between spec files. Could you please tell me the exact version in which it was still working for you? Thank you!

**Comment by javierbrea** [comment]
> 

Update: It doesn't work either with version 9.0.0

**Comment by vdineva** [comment]
Our current version of Cypress is 9.7.0 and things work fine. We've had every other 9.x.x version installed and things were working fine. In our case localStorage is not retained between soec files once we upgrade to v10 of Cypress

**Comment by javierbrea** [comment]
@vdineva Could it be related to the new configuration files on Cypress 10 instead of the plugin itself? I mean, maybe the commands were not being installed properly. But I suppose that this would produce an error when trying to use them, it wouldn't produce such a specific bug. In order to understand it better, was the localStorage retained between tests in the same spec file properly in Cypress 10 in your case?

Anyway, I have already found a solution. But I'd like to understand why was this happening. I suspect that in this issue there are problems related to the localStorage not being maintained between specs (which I have checked that was happening in previous versions already), and problems related to not installing the plugin properly in Cypress 10.

I will publish the new version soon, and I will also update the installation docs. Apart from this, I will add also E2E tests using Cypress 9, and I'll keep a branch with the Cypress 9 failing tests before applying the fix, just in case it may be useful for further investigation. 

Thanks for your fast reply, by the way! 😃
